version: "2.3"
networks:
  default:
    driver: bridge

services:
  mysql:
    container_name: teste-mysql
    image: mysql:5.7
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    restart: always
    volumes:
      - ./teste-inicio.sql:/docker-entrypoint-initdb.d/inicio.sql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

  sqlpad:
    image: sqlpad/sqlpad:6
    hostname: 'sqlpad'
    ports:
      - ${SQLPAD_PORT}:${SQLPAD_PORT}
    restart: always
    depends_on:
      - mysql
    environment:
      SQLPAD_ADMIN: ${SQLPAD_ADMIN}
      SQLPAD_ADMIN_PASSWORD: ${SQLPAD_ADMIN_PASSWORD}
      SQLPAD_CONNECTIONS__sqlserverdemo__name: SQL Server Demo
      SQLPAD_CONNECTIONS__sqlserverdemo__driver: mysql
      SQLPAD_CONNECTIONS__sqlserverdemo__host: ${SQLPAD_HOST}
      SQLPAD_CONNECTIONS__sqlserverdemo__database: ${MYSQL_DATABASE}
      SQLPAD_CONNECTIONS__sqlserverdemo__username: ${MYSQL_USER}
      SQLPAD_CONNECTIONS__sqlserverdemo__password: ${MYSQL_PASSWORD}
    volumes:
      - sqlpad-volume:/var/lib/sqlpad

  nestjs:
    container_name: nestjs
    build: "./datapage-nodejs"
    restart: unless-stopped
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - mysql
    volumes:
      - ./datapage-nodejs:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  sqlpad-volume: